name: Deployment pipeline

on:
  push:
    branches:
      -main
jobs: 
    simple_deployment_pipeline:
      runs-on: ubuntu-20.04
      steps:
        - uses: action/checkout@v4
        - uses: action/setup-node@v4
          with: 
            node-version: '20'
        - name: Install depenencies
          run: npm install
        - name: Check style
          run: npm run eslint
