name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm install 

      - name: Check style
        run: npm run eslint
      - name: Check build
        run: npm run build
      
      - name: Do tests
        run: npm run test
        
      
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip')
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
      - name: debug Webhook URL
        run: echo "Webhook is set"
        env:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Success
        if: success()
        run: |
            curl -H "Content-Type: application/json" \
            -d "{\"content\":\"✅ Test Succeeded!\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
  
      - name: Test Failure
        if: failure()
        run: |
            curl -H "Content-Type: application/json" \
            -d "{\"content\":\"❌ Test Failed!\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
  
      - name: Test Cancelled
        if: cancelled()
        run: |
            curl -H "Content-Type: application/json" \
            -d "{\"content\":\"⚠️ Test Cancelled!\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}

  tag_realase:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Bump patch version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        if:  github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify_discord:
    needs: [tag_realase]
    runs-on: ubuntu-20.04
    steps:
      - name: Notify Discord
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip')
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 New release pushed to main!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
